[package]
name = "cve-rs"
description = "Blazingly fast memory vulnerabilities, written in 100% safe Rust."
authors = ["Speykious", "BrightShard", "Creative0708"]
version = "0.3.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/Speykious/cve-rs"
categories = ["rust-patterns"]
keywords = ["cve", "security", "soundness", "safety", "segfault"]

[dependencies]
oorandom = { version = "11.1.3", optional = true }

[profile.dev]
debug = false

[features]
default = []
give-up = ["oorandom"]
