[package]
name = "cve-rs"
description = "Blazingly fast memory vulnerabilities, written in 100% safe Rust."
authors = ["Speykious", "BrightShard", "Creative0708"]
version = "0.2.0"
edition = "2021"
license = "BSD-2-Clause"
repository = "https://github.com/Speykious/cve-rs"
categories = ["rust-patterns"]
keywords = ["cve", "security", "soundness", "safety", "segfault"]

[profile.dev]
debug = false
