[package]
name = "cve-rs"
description = "Blazingly fast CVEs, written in 100% safe Rust."
authors = ["Speykious", "BrightShard", "Creative0708"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Speykious/cve-rs"
license = "BSD-2-Clause"
keywords = ["cve", "security", "soundness", "safety", "segfault"]
categories = ["rust-patterns"]

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }

[profile.dev]
debug = false
