
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test suite
    runs-on:
      - ubuntu-latest
      - windows-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test

  test-release:
    name: Test suite
    runs-on:
      - ubuntu-latest
      - windows-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --release